const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
require('dotenv').config();
const Course = require('./models/Course');
const User = require('./models/User');
const Quiz = require('./models/Quiz');
const Assignment = require('./models/Assignment');
const Enrollment = require('./models/Enrollment');
const Certificate = require('./models/Certificate');

const seedEnterpriseData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/learnx');
    console.log('Connected to DB');

    let instructor = await User.findOne({ role: 'admin' });
    if (!instructor) {
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash('admin123', salt);
        instructor = await User.create({
            name: 'System Admin',
            email: 'admin@system.local',
            password: hashedPassword,
            firebaseUid: 'dummy_firebase_uid_123_enterprise',
            role: 'admin'
        });
    }

    // Clean up old courses and quizzes generated by scripts
    console.log('Cleaning up old data...');
    const titlesToDelete = [
      'Data Structures & Algorithms (DSA)',
      'Data Structures & Algorithms Masterclass',
      'Operating System',
      'Operating Systems Mastery',
      'Operating Systems Essentials',
      'Computer Networks',
      'Computer Networks Fundamentals',
      'System Design',
      'System Design for Interviews',
      'QALR (Quantitative Aptitude & Logical Reasoning)',
      'Quantitative Aptitude & Logical Reasoning',
      'Quantitative Aptitude Masterclass'
    ];
    
    const coursesToDelete = await Course.find({ title: { $in: titlesToDelete } });
    const courseIds = coursesToDelete.map(c => c._id);
    if (courseIds.length > 0) {
        await Quiz.deleteMany({ course: { $in: courseIds } });
        await Assignment.deleteMany({ course: { $in: courseIds } });
        await Enrollment.deleteMany({ course: { $in: courseIds } });
        await Certificate.deleteMany({ course: { $in: courseIds } });
    }
    
    await Course.deleteMany({ title: { $in: titlesToDelete } });
    
    // Helper to create a generic quiz
    const createQuiz = async (title, numQuestions, courseId) => {
        const questions = [];
        for (let i = 1; i <= numQuestions; i++) {
            questions.push({
                questionText: `Sample Question ${i} for ${title}. Which option is correct?`,
                type: 'SingleCorrect',
                options: ['Option A', 'Option B', 'Option C', 'Option D'],
                correctAnswers: ['Option A'],
                explanation: 'Option A is the correct choice because of standard computing principles.'
            });
        }
        
        const quiz = await Quiz.create({
            title,
            description: `Assessment for ${title}`,
            course: courseId, // Optional, we will link it
            questions,
            createdBy: instructor._id
        });
        
        return quiz._id.toString();
    };

    console.log('Generating DSA Course...');
    const dsaCourse = new Course({
        title: 'Data Structures & Algorithms Masterclass',
        description: 'Complete DSA bootcamp from 0 to 100%. Master time complexity, arrays, strings, trees, graphs, and dynamic programming.',
        category: 'DSA',
        instructor: instructor._id,
        difficulty: 'Hard',
        modules: []
    });
    
    const dsaModules = [
        { title: 'Introduction to DSA', topics: ['What is DSA', 'Why DSA', 'Time Complexity', 'Space Complexity', 'Big O Notation'], quizQ: 10 },
        { title: 'Arrays', topics: ['Array Basics', 'Traversal', 'Insertion', 'Deletion', 'Prefix Sum', 'Sliding Window'], quizQ: 15 },
        { title: 'Strings', topics: ['String Operations', 'Palindrome', 'Anagram', 'Hashing', 'KMP', 'Rabin Karp'], quizQ: 15 },
        { title: 'Linked Lists', topics: ['Singly Linked List', 'Doubly Linked List', 'Circular Linked List', 'Reverse Linked List'], quizQ: 15 },
        { title: 'Stacks & Queues', topics: ['Stack', 'Queue', 'Monotonic Stack', 'Circular Queue'], quizQ: 15 },
        { title: 'Trees', topics: ['Binary Tree', 'BST', 'Heap', 'Trie'], quizQ: 20 },
        { title: 'Graphs', topics: ['BFS', 'DFS', 'Topological Sort', 'Dijkstra', 'MST'], quizQ: 20 },
        { title: 'Dynamic Programming', topics: ['Memoization', 'Tabulation', 'Knapsack', 'LIS', 'LCS'], quizQ: 20 }
    ];

    for (const mod of dsaModules) {
        const lessons = [];
        // Topic Explanation Lesson
        lessons.push({
            title: `Topic Explanation: ${mod.title}`,
            type: 'article',
            duration: 30,
            content: `### ${mod.title}\n\n**Topics Covered:**\n${mod.topics.map(t => '- ' + t).join('\n')}\n\nThis module covers everything from basics to advanced patterns. Ensure you practice coding the algorithms from scratch.\n\n\`\`\`javascript\n// Example Code Template\nfunction solveProblem() {\n    console.log("Mastering ${mod.title}");\n}\n\`\`\``
        });
        
        // Practice/Assignment Lesson
        lessons.push({
            title: `Practice Questions: ${mod.title}`,
            type: 'assignment',
            duration: 60,
            content: `### Assignment\n\nImplement the core concepts of ${mod.title}. Write code to solve 3 classic problems associated with this topic on LeetCode/HackerRank.`
        });
        
        // Quiz Lesson
        const quizId = await createQuiz(`Quiz: ${mod.title}`, mod.quizQ, null);
        lessons.push({
            title: `Module Assessment: ${mod.title} (${mod.quizQ} MCQs)`,
            type: 'quiz',
            duration: 20,
            refId: quizId
        });
        
        dsaCourse.modules.push({
            title: mod.title,
            description: `Master ${mod.title} with in-depth explanations and code examples.`,
            lessons
        });
    }
    
    // Final Assessment
    const dsaFinalQuizId = await createQuiz('DSA Final Assessment', 50, null);
    dsaCourse.finalAssessment = dsaFinalQuizId;
    await dsaCourse.save();


    console.log('Generating OS Course...');
    const osCourse = new Course({
        title: 'Operating Systems Mastery',
        description: 'Deep dive into process scheduling, memory management, deadlocks, and file systems.',
        category: 'Operating System',
        instructor: instructor._id,
        difficulty: 'Medium',
        modules: []
    });
    
    const osTopics = ['OS Introduction', 'Processes', 'Threads', 'Scheduling Algorithms', 'Synchronization', 'Deadlocks', 'Memory Management', 'Paging', 'Virtual Memory', 'File Systems', 'Linux Basics'];
    for (const topic of osTopics) {
        const quizId = await createQuiz(`Quiz: ${topic}`, 10, null);
        osCourse.modules.push({
            title: topic,
            lessons: [
                { title: `Explanation: ${topic}`, type: 'article', duration: 25, content: `### ${topic}\nLearn the fundamentals of ${topic} with visual diagrams and interview questions.` },
                { title: `Quiz: ${topic} (10 MCQs)`, type: 'quiz', duration: 15, refId: quizId }
            ]
        });
    }
    const osFinalQuizId = await createQuiz('OS Final Assessment', 50, null);
    osCourse.finalAssessment = osFinalQuizId;
    await osCourse.save();


    console.log('Generating Computer Networks Course...');
    const cnCourse = new Course({
        title: 'Computer Networks Fundamentals',
        description: 'Complete guide to the OSI Model, TCP/IP, IP Addressing, Routing, and Security.',
        category: 'Computer Network',
        instructor: instructor._id,
        difficulty: 'Medium',
        modules: []
    });
    
    const cnTopics = ['Network Basics', 'OSI Model', 'TCP/IP', 'IP Addressing', 'Subnetting', 'DNS', 'HTTP/HTTPS', 'Routing', 'Switching', 'Network Security', 'Cloud Networking'];
    for (const topic of cnTopics) {
        const quizId = await createQuiz(`Quiz: ${topic}`, 10, null);
        cnCourse.modules.push({
            title: topic,
            lessons: [
                { title: `Explanation: ${topic}`, type: 'article', duration: 25, content: `### ${topic}\nLearn the fundamentals of ${topic} with visual diagrams and interview questions.` },
                { title: `Quiz: ${topic} (10 MCQs)`, type: 'quiz', duration: 15, refId: quizId }
            ]
        });
    }
    const cnFinalQuizId = await createQuiz('Computer Networks Final Assessment', 50, null);
    cnCourse.finalAssessment = cnFinalQuizId;
    await cnCourse.save();


    console.log('Generating System Design Course...');
    const sdCourse = new Course({
        title: 'System Design for Interviews',
        description: 'Learn how to design scalable and distributed systems. Covers Load Balancers, Caching, Databases, Sharding, and Microservices.',
        category: 'System Design',
        instructor: instructor._id,
        difficulty: 'Hard',
        modules: []
    });
    
    const sdTopics = ['Scalability', 'Load Balancers', 'Caching', 'Databases', 'Replication', 'Sharding', 'Message Queues', 'Microservices', 'Distributed Systems', 'CAP Theorem', 'Design Patterns'];
    for (const topic of sdTopics) {
        const quizId = await createQuiz(`Quiz: ${topic}`, 10, null);
        sdCourse.modules.push({
            title: topic,
            lessons: [
                { title: `Explanation: ${topic}`, type: 'article', duration: 30, content: `### ${topic}\nExplore distributed system architectures regarding ${topic}.` },
                { title: `Quiz: ${topic}`, type: 'quiz', duration: 15, refId: quizId }
            ]
        });
    }
    
    // Add case studies module
    sdCourse.modules.push({
        title: 'System Design Case Studies',
        description: 'Real world examples',
        lessons: [
            { title: 'Case Study: URL Shortener', type: 'article', duration: 40, content: 'Design a service like TinyURL.' },
            { title: 'Case Study: WhatsApp', type: 'article', duration: 40, content: 'Design a real-time chat application.' },
            { title: 'Case Study: Netflix', type: 'article', duration: 40, content: 'Design a global video streaming platform.' },
            { title: 'Case Study: Uber', type: 'article', duration: 40, content: 'Design a ride-hailing service.' },
            { title: 'Case Study: Instagram', type: 'article', duration: 40, content: 'Design a photo-sharing social network.' }
        ]
    });
    
    const sdFinalQuizId = await createQuiz('System Design Final Assessment', 50, null);
    sdCourse.finalAssessment = sdFinalQuizId;
    await sdCourse.save();


    console.log('Generating Quantitative Aptitude Course...');
    const quantCourse = new Course({
        title: 'Quantitative Aptitude & Logical Reasoning',
        description: 'Master mathematical concepts and logical reasoning for placements and competitive programming.',
        category: 'Aptitude',
        instructor: instructor._id,
        difficulty: 'Easy',
        modules: []
    });
    
    const quantTopics = ['Percentages', 'Ratio & Proportion', 'Profit & Loss', 'Time & Work', 'Time Speed Distance', 'Probability', 'Permutation & Combination', 'Data Interpretation'];
    const logicTopics = ['Coding Decoding', 'Blood Relations', 'Directions', 'Seating Arrangement', 'Puzzles', 'Syllogisms', 'Critical Reasoning'];
    
    for (const topic of [...quantTopics, ...logicTopics]) {
        const quizId = await createQuiz(`Quiz: ${topic}`, 15, null);
        quantCourse.modules.push({
            title: topic,
            lessons: [
                { title: `Explanation & Solved Examples: ${topic}`, type: 'article', duration: 35, content: `### ${topic}\nDetailed explanations and step-by-step solved examples.` },
                { title: `Practice Assignment: ${topic}`, type: 'assignment', duration: 40, content: 'Solve these 5 practice questions.' },
                { title: `Quiz: ${topic} (15 MCQs)`, type: 'quiz', duration: 20, refId: quizId }
            ]
        });
    }
    
    const quantFinalQuizId = await createQuiz('Placement Final Test', 100, null);
    quantCourse.finalAssessment = quantFinalQuizId;
    await quantCourse.save();

    console.log('✅ Seeding enterprise courses completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedEnterpriseData();
